apiVersion: batch/v1
kind: Job
metadata:
  name: math-job
spec:
  template:
    spec:
      containers:
      - name: math-container
        image: math-evaluator:1.1
        env:
        - name: MATH_EXPRESSION
          value: "10*(5+2)-3"
      restartPolicy: Never
  backoffLimit: 2

